spring.application.name=analytics

spring.datasource.url=jdbc:postgresql://localhost:5432/BAV_HML
spring.datasource.username=postgres
spring.datasource.password=D23m02@93
spring.jpa.hibernate.ddl-auto=none


